name: Simple Portfolio Check

on:
  workflow_dispatch:  # Only manual triggers
  schedule:
    - cron: '0 14 * * 1-5'  # Weekdays at 2 PM UTC

jobs:
  check_portfolio:
    runs-on: ubuntu-latest
    
    steps:
    - name: Setup
      run: |
        echo "Starting portfolio monitoring..."
        python3 --version
        
    - name: Install Python packages
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install yfinance pandas requests
        
    - name: Create monitoring script
      run: |
        cat > simple_monitor.py << 'EOF'
        import yfinance as yf
        import pandas as pd
        from datetime import datetime
        
        # Simple portfolio check
        symbols = ["AAPL", "MSFT", "GOOGL"]  # Example symbols
        
        print(f"Portfolio Check - {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
        print("-" * 50)
        
        for symbol in symbols:
            try:
                ticker = yf.Ticker(symbol)
                info = ticker.info
                
                current_price = info.get('currentPrice', 'N/A')
                pe_ratio = info.get('pe', 'N/A')
                
                print(f"{symbol}: ${current_price} (P/E: {pe_ratio})")
                
            except Exception as e:
                print(f"{symbol}: Error - {e}")
        
        print("-" * 50)
        print("Portfolio check completed")
        EOF
        
    - name: Run monitoring
      run: |
        python3 simple_monitor.py
