name: Automated Portfolio Monitoring

on:
  schedule:
    # Run Monday-Friday at 9 AM EST (14:00 UTC)
    - cron: '0 14 * * 1-5'
    # Run Monday mornings for weekly report
    - cron: '0 13 * * 1'
  workflow_dispatch:  # Allow manual triggers

jobs:
  portfolio_monitoring:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install yfinance pandas
        
    - name: Run Portfolio Monitoring
      env:
        PORTFOLIO_SYMBOLS: ${{ secrets.PORTFOLIO_SYMBOLS }}
        ALERT_EMAIL: ${{ secrets.ALERT_EMAIL }}
        GMAIL_USER: ${{ secrets.GMAIL_USER }}
        GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
        SEND_SCHEDULED_REPORTS: ${{ github.event.schedule == '0 13 * * 1' && 'true' || 'false' }}
      run: python automated_monitor.py
      
    - name: Upload results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: monitoring-results
        path: |
          previous_scores.json
        retention-days: 30
